name: Release to Cloudflare pages

on:
  push:
    branches:
      - main

jobs:
  CF-production-deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Setup Rust
        run: |
          rustup target add wasm32-unknown-unknown
          cargo clippy
          cargo fmt --check

      - name: Download and install Trunk library
        run: wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.18.2/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      - name: Build with Trunk
        run: ./trunk build --release

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=pod-leo-works
